"""Alembic environment for the DeployAI Control Plane.

Story 1.3 scaffolded async Alembic against an empty ``target_metadata``.
Story 1.8 wires ``control_plane.domain.base.Base.metadata`` so autogenerated
migrations (Story 1.9+) pick up the canonical-memory tables.

Operates in both async and sync modes:

- Production / local dev: ``postgresql+asyncpg://...`` → async branch.
- Integration tests (Story 1.8): ``postgresql+psycopg://...`` or plain
  ``postgresql://...`` → sync branch. Testcontainers hands back a sync
  URL; running migrations through an async engine on a sync URL would
  force a second dependency just to satisfy Alembic's plumbing.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# Ensure the ``control_plane.domain.canonical_memory`` package is imported
# so every table registers onto ``Base.metadata`` before Alembic reads it.
from control_plane.domain import adjudication as _adjudication  # noqa: F401
from control_plane.domain import tenant_phase as _tenant_phase  # noqa: F401
from control_plane.domain import app_identity as _app_identity  # noqa: F401
from control_plane.domain import break_glass as _break_glass  # noqa: F401
from control_plane.domain import canonical_memory as _canonical_memory  # noqa: F401
from control_plane.domain import integrations as _integrations  # noqa: F401
from control_plane.domain.base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _is_async_url(url: str | None) -> bool:
    """Return True when the configured URL points at an asyncio driver."""

    return bool(url) and "+asyncpg" in str(url)


def run_migrations_offline() -> None:
    """Offline mode — emit SQL to stdout without opening a connection."""

    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Async path — asyncpg driver (production, local dev)."""

    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_sync_migrations() -> None:
    """Sync path — psycopg/psycopg2 driver (integration tests)."""

    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        do_run_migrations(connection)

    connectable.dispose()


def run_migrations_online() -> None:
    """Online mode — dispatches to async or sync based on URL driver."""

    url = config.get_main_option("sqlalchemy.url")
    if _is_async_url(url):
        asyncio.run(run_async_migrations())
    else:
        run_sync_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
