"""Per-engagement configuration for the 5-engagement portfolio fixture."""

from __future__ import annotations

from dataclasses import dataclass

PORTFOLIO_TENANT_ID = "11111111-1111-1111-1111-111111111111"


@dataclass(frozen=True)
class Stakeholder:
    short: str
    full_name: str
    role: str


@dataclass(frozen=True)
class SystemTitle:
    title: str
    intro_week: int


@dataclass(frozen=True)
class EngagementConfig:
    engagement_id: str
    name: str
    customer_account: str
    industry: str
    phase: str
    namespace: str
    stakeholders: tuple[Stakeholder, ...]
    departed_short_names: tuple[str, ...]
    systems: tuple[SystemTitle, ...]
    decision_titles: tuple[tuple[int, str], ...]
    risk_titles: tuple[tuple[int, str], ...]
    commitments: tuple[tuple[int, str], ...]


_NORTHWIND = EngagementConfig(
    engagement_id="f1f1f1f1-f1f1-4f1f-8f1f-f1f1f1f1f1f1",
    name="Northwind Logistics — Warehouse Management Replatform",
    customer_account="Northwind Logistics",
    industry="logistics",
    phase="build",
    namespace="northwind",
    stakeholders=(
        Stakeholder("kowalski", "Henryk Kowalski", "VP Operations"),
        Stakeholder("delacroix", "Margaux Delacroix", "Director of Logistics"),
        Stakeholder("oduya", "Femi Oduya", "Warehouse Systems Lead"),
        Stakeholder("brennan", "Cillian Brennan", "Compliance Officer"),
        Stakeholder("hartwell", "Imogen Hartwell", "Procurement Manager"),
        Stakeholder("nakata", "Souta Nakata", "Network Engineering"),
        Stakeholder("ferreira", "Lucia Ferreira", "Floor Supervisor"),
        Stakeholder("yardley", "Tobias Yardley", "Inventory Analyst"),
        Stakeholder("okwuosa", "Adaeze Okwuosa", "Change Management"),
        Stakeholder("varga", "Janos Varga", "Carrier Integration"),
        Stakeholder("brindle", "Honora Brindle", "QA Lead"),
        Stakeholder("seppanen", "Mikko Seppanen", "DevOps"),
    ),
    departed_short_names=("yardley", "brindle"),
    systems=(
        SystemTitle("WMS Core (Manhattan)", 1),
        SystemTitle("Carrier EDI Gateway", 1),
        SystemTitle("Conveyor Control Service", 2),
        SystemTitle("Pick-and-Pack App", 3),
        SystemTitle("Slotting Optimizer", 4),
        SystemTitle("Yard Management Module", 5),
    ),
    decision_titles=(
        (1, "Adopt Manhattan Active WMS as the platform of record"),
        (2, "Migrate EDI gateway to Cleo for partner onboarding"),
        (3, "Stage rollout warehouse-by-warehouse, Atlanta first"),
        (4, "Replace handheld scanners with iOS PWA pickers"),
        (5, "Use Apache Kafka for slot-change events"),
        (6, "Keep conveyor PLCs on legacy network for cycle 1"),
        (7, "Adopt centralized exception queue across DCs"),
        (8, "Defer carrier rate-shopping rewrite to phase 2"),
        (9, "Lock down PII handling for shipper records"),
        (10, "Move slotting model from SAS to Python"),
        (11, "Adopt Datadog for fleet observability"),
        (12, "Run parallel WMS for cutover weekend"),
        (13, "Hold weekly DC ops sync at 8am ET"),
        (14, "Schema migration to Postgres 16 in flight"),
        (15, "Adopt CloudFront for ASN portal"),
        (16, "Move carrier auth to mTLS"),
        (17, "Restrict scanner roles per-DC"),
        (18, "Accept 4-hour batch lag for slotting refresh"),
        (19, "Replatform yard management onto Maven"),
        (20, "Defer carrier 3PL integration until Q3"),
        (21, "Add carrier SLA monitoring"),
        (22, "Tighten pick-error escalation cadence"),
        (23, "Final approval for Atlanta launch"),
        (24, "Approve carrier-fee passthrough"),
        (25, "Approve post-launch DR drill cadence"),
    ),
    risk_titles=(
        (4, "Carrier EDI partner Cleo backlog risks W18 cutover"),
        (5, "Atlanta DC labor shortage forecast for Q2"),
        (6, "Scanner PWA offline-mode parity behind plan"),
        (7, "Slot optimizer SLA degradation vs SAS baseline"),
        (8, "WMS reporting parity with Manhattan SCALE gap"),
        (10, "Kafka partition rebalance risk during peak"),
        (11, "DC network segmentation slows PLC sync"),
        (13, "Carrier 3PL contract terms unresolved"),
        (14, "Pick-error rate elevated in pilot wave"),
        (15, "Procurement delay on iOS device fleet"),
        (16, "Kowalski escalation backlog growing"),
        (18, "Conveyor downtime trends upward"),
        (19, "Inventory variance widening in legacy DCs"),
        (21, "Cutover weekend coverage thin"),
        (22, "Audit log retention policy unresolved"),
    ),
    commitments=(
        (8, "Atlanta DC live by W18"),
        (16, "Carrier EDI compliance signed"),
        (20, "Phase 2 plan presented to ops board"),
        (26, "Post-launch DR drill scheduled"),
    ),
)

_ACME_FIN = EngagementConfig(
    engagement_id="f2f2f2f2-f2f2-4f2f-8f2f-f2f2f2f2f2f2",
    name="Acme Financial — Compliance Reporting Migration",
    customer_account="Acme Financial",
    industry="financial-services",
    phase="build",
    namespace="acme_financial",
    stakeholders=(
        Stakeholder("calloway", "Beatrix Calloway", "Chief Compliance Officer"),
        Stakeholder("eskridge", "Donovan Eskridge", "Head of Regulatory Reporting"),
        Stakeholder("nikolaidis", "Stelios Nikolaidis", "Risk Architecture"),
        Stakeholder("whittaker", "Persephone Whittaker", "Data Governance Lead"),
        Stakeholder("oyelaran", "Ifedayo Oyelaran", "Audit Liaison"),
        Stakeholder("torquato", "Cesare Torquato", "Treasury Tech"),
        Stakeholder("braithwaite", "Anneliese Braithwaite", "BSA/AML Lead"),
        Stakeholder("kashiwagi", "Rena Kashiwagi", "Counterparty Risk"),
        Stakeholder("villalobos", "Catalina Villalobos", "Reporting Engineering"),
        Stakeholder("eklund", "Vidar Eklund", "Infra Reliability"),
        Stakeholder("rasmussen", "Iben Rasmussen", "Vendor Risk"),
    ),
    departed_short_names=("torquato",),
    systems=(
        SystemTitle("FRY-9C Reporting Engine", 1),
        SystemTitle("CCAR Stress Pipeline", 1),
        SystemTitle("Counterparty Graph (Neo4j)", 2),
        SystemTitle("AML Transaction Monitor", 3),
        SystemTitle("Regulatory Lineage Service", 4),
        SystemTitle("Trade Capture Adapter", 5),
    ),
    decision_titles=(
        (1, "Adopt Wolters Kluwer OneSumX for FRY-9C"),
        (2, "Move CCAR stress runs onto Databricks"),
        (3, "Standardize on FRTB-compliant data model"),
        (4, "Counterparty graph in Neo4j Aura"),
        (5, "Adopt Collibra for data governance"),
        (6, "Encrypt at rest with HSM-backed keys"),
        (7, "Establish quarterly attestation cadence"),
        (8, "Migrate AML rules from legacy Actimize"),
        (9, "Adopt change-control gates per submission"),
        (10, "Use dbt for regulatory lineage"),
        (11, "Vendor risk attestations digitized"),
        (12, "Restrict reporting reads to least-privilege"),
        (13, "Maintain legacy parallel for 2 cycles"),
        (14, "Sign off on schedule HC migration"),
        (15, "Approve external auditor sandbox access"),
        (16, "Treasury feed contract refresh"),
        (17, "Adopt PII tokenization in pipeline"),
        (18, "Reduce nightly batch SLA from 8h to 5h"),
        (19, "Quarterly DR exercise approved"),
        (20, "Final FRY-9C dual-run sign-off"),
        (21, "Tighten AML alert review SLO"),
        (22, "Stress-test calibration committee approval"),
        (23, "Approve Q4 regulatory submission plan"),
        (24, "Accept Collibra-OneSumX integration trade-off"),
        (25, "Approve attestation rollout to subsidiaries"),
    ),
    risk_titles=(
        (3, "OneSumX vendor SLA lacks dual-run guarantees"),
        (5, "Neo4j cardinality blow-up in counterparty graph"),
        (6, "AML false-positive rate creeping above target"),
        (8, "Data lineage gap for legacy treasury feed"),
        (9, "Auditor sandbox readiness behind schedule"),
        (10, "FRTB SA-CCR calibration disputed"),
        (12, "Vendor risk attestation backlog"),
        (13, "Token vault throughput insufficient"),
        (14, "FRY-9C HC schedule cutover narrowing"),
        (15, "AML model governance docs incomplete"),
        (17, "Stress scenario library lacks 2008 baseline"),
        (19, "DR runbook out of date"),
        (20, "Reporting SLA at risk during cutover"),
        (22, "Audit committee escalation pending"),
        (23, "Subsidiary attestation onboarding slow"),
    ),
    commitments=(
        (10, "Auditor sandbox handed over"),
        (16, "Dual-run for FRY-9C Q3 signed off"),
        (22, "Subsidiary onboarding plan complete"),
        (26, "Regulatory submission window confirmed"),
    ),
)

_GREENFIELD = EngagementConfig(
    engagement_id="f3f3f3f3-f3f3-4f3f-8f3f-f3f3f3f3f3f3",
    name="Greenfield Energy — Field Operations System",
    customer_account="Greenfield Energy",
    industry="energy",
    phase="build",
    namespace="greenfield",
    stakeholders=(
        Stakeholder("dwyer", "Saoirse Dwyer", "VP Field Operations"),
        Stakeholder("amaechi", "Tobenna Amaechi", "Director of Reliability"),
        Stakeholder("lindqvist", "Magnus Lindqvist", "SCADA Architect"),
        Stakeholder("yamasaki", "Ryosuke Yamasaki", "OT Security"),
        Stakeholder("perales", "Esteban Perales", "Pipeline Engineering"),
        Stakeholder("bramwell", "Ottoline Bramwell", "Environmental & Safety"),
        Stakeholder("zaytsev", "Yegor Zaytsev", "Mobile Workforce Platform"),
        Stakeholder("oluwasanmi", "Folake Oluwasanmi", "Asset Management"),
        Stakeholder("hellquist", "Tilda Hellquist", "Data Platform"),
        Stakeholder("rocafuerte", "Mateo Rocafuerte", "Regulatory Affairs"),
        Stakeholder("sigurdsson", "Bjarni Sigurdsson", "Drone Inspections"),
    ),
    departed_short_names=("zaytsev", "bramwell"),
    systems=(
        SystemTitle("SCADA Historian (OSIsoft)", 1),
        SystemTitle("Field Service Mobile App", 1),
        SystemTitle("Work Order Engine (IBM Maximo)", 2),
        SystemTitle("OT-to-IT Gateway", 3),
        SystemTitle("Pipeline Integrity Service", 4),
        SystemTitle("Drone Imagery Pipeline", 5),
    ),
    decision_titles=(
        (1, "Adopt Maximo as system of record for assets"),
        (2, "Modernize SCADA historian to PI Cloud"),
        (3, "Mobile-first FSM rebuild on React Native"),
        (4, "OT/IT segmentation via Claroty"),
        (5, "Drone imagery on AWS GroundTruth"),
        (6, "Pipeline integrity ML on Sagemaker"),
        (7, "Adopt OPC-UA across PLC fleet"),
        (8, "Workforce scheduling rebuild deferred to phase 2"),
        (9, "Adopt MQTT broker for telemetry"),
        (10, "Centralize asset taxonomy"),
        (11, "Compliance reporting via Cority"),
        (12, "Adopt Snowflake for analytics"),
        (13, "Tighten cyber-physical incident response"),
        (14, "Drone inspection cadence quarterly"),
        (15, "Standardize on Geographic Information System (GIS)"),
        (16, "Field crew handheld refresh"),
        (17, "Approve OT vendor onboarding policy"),
        (18, "Adopt zero-trust for OT segments"),
        (19, "Migrate historian pilot to AWS US-East"),
        (20, "Approve emergency dispatch workflow rebuild"),
        (21, "Standardize incident classification"),
        (22, "Approve Q3 outage drill cadence"),
        (23, "Final go on west region rollout"),
        (24, "Approve drone vendor selection"),
        (25, "Approve pipeline integrity ML production cutover"),
    ),
    risk_titles=(
        (3, "OT segmentation lagging on legacy PLCs"),
        (4, "Maximo upgrade dependency on Db2 deprecation"),
        (5, "Drone imagery storage cost overrun"),
        (6, "Mobile app offline sync gaps in remote regions"),
        (8, "OPC-UA adoption stalled on older vendors"),
        (10, "ML model bias on pipeline anomaly classifier"),
        (11, "Crew scheduling overtime spike forecast"),
        (13, "Carrier weather disruptions delaying rollouts"),
        (14, "Regulatory reporting timeline tightening"),
        (15, "GIS data quality below threshold"),
        (17, "OT vendor patch cadence inconsistent"),
        (18, "Drone vendor consolidation risk"),
        (20, "Outage drill participation low"),
        (22, "West region rollout staffing thin"),
        (23, "Field crew retention pressure"),
    ),
    commitments=(
        (9, "OT/IT segmentation pilot live"),
        (16, "Field service mobile launched in pilot region"),
        (22, "West region rollout plan signed off"),
        (26, "Q4 outage drill scheduled"),
    ),
)

_BEACON = EngagementConfig(
    engagement_id="f4f4f4f4-f4f4-4f4f-8f4f-f4f4f4f4f4f4",
    name="Beacon Healthcare — Provider Directory Modernization",
    customer_account="Beacon Healthcare",
    industry="healthcare",
    phase="build",
    namespace="beacon",
    stakeholders=(
        Stakeholder("morrigan", "Aoife Morrigan", "VP Provider Networks"),
        Stakeholder("achebe", "Chukwuemeka Achebe", "Director of Credentialing"),
        Stakeholder("kovalenko", "Olesya Kovalenko", "FHIR Integration Lead"),
        Stakeholder("delavega", "Eulalia de la Vega", "Member Services"),
        Stakeholder("salander", "Astrid Salander", "Provider Operations"),
        Stakeholder("ozawa", "Hideo Ozawa", "Identity & Access"),
        Stakeholder("kabir", "Tariq Kabir", "Data Quality"),
        Stakeholder("rohrer", "Annika Rohrer", "Regulatory Reporting"),
        Stakeholder("appiah", "Akosua Appiah", "Customer Care"),
        Stakeholder("svobodova", "Pavlina Svobodova", "Vendor Management"),
        Stakeholder("magalhaes", "Eliana Magalhaes", "Clinical Informatics"),
    ),
    departed_short_names=("appiah",),
    systems=(
        SystemTitle("Provider Directory Service", 1),
        SystemTitle("FHIR Directory API", 1),
        SystemTitle("Credentialing Workflow", 2),
        SystemTitle("Member-facing Search UI", 3),
        SystemTitle("Provider Identity Vault", 4),
        SystemTitle("Claims Routing Adapter", 5),
    ),
    decision_titles=(
        (1, "Adopt FHIR R4 provider directory schema"),
        (2, "Replace homegrown credentialing engine"),
        (3, "Build new member-facing provider search UI"),
        (4, "Adopt CAQH ProView for primary source verification"),
        (5, "Identity vault on AWS Cognito"),
        (6, "Adopt event-driven sync to claims systems"),
        (7, "Centralize provider taxonomy"),
        (8, "Defer provider analytics dashboard to phase 2"),
        (9, "Adopt OpenAPI contract testing"),
        (10, "Standardize provider deduplication rules"),
        (11, "Multi-region active-passive deployment"),
        (12, "Vendor BAA refresh signed"),
        (13, "Adopt FHIR-compliant audit logging"),
        (14, "PHI tokenization for analytics layer"),
        (15, "Approve credentialing SLA targets"),
        (16, "Adopt directory accuracy attestation flow"),
        (17, "Tighten member-facing CCPA disclosure"),
        (18, "Establish per-state network reporting"),
        (19, "Final review of provider data model"),
        (20, "Approve provider self-service portal"),
        (21, "Defer Medicare Advantage network until Q4"),
        (22, "Sign off on CAQH integration scope"),
        (23, "Approve regional pilot launch"),
        (24, "Approve provider taxonomy migration"),
        (25, "Approve quarterly provider attestation cadence"),
    ),
    risk_titles=(
        (3, "FHIR schema drift across plan ecosystem"),
        (4, "Credentialing backlog inherited from legacy"),
        (5, "Provider dedupe false-positive rate"),
        (6, "CAQH SLA gaps during peak season"),
        (8, "Identity vault migration cutover risk"),
        (9, "Provider attestation participation low"),
        (10, "Vendor BAA renewal slipping"),
        (11, "Member search UX accessibility gaps"),
        (12, "Cross-region failover untested"),
        (14, "PHI tokenization SLA risk"),
        (16, "Regional pilot staffing thin"),
        (18, "State-level reporting deadlines tightening"),
        (20, "Claims routing adapter latency"),
        (22, "Provider self-service onboarding slow"),
        (23, "Directory accuracy KPI below threshold"),
    ),
    commitments=(
        (10, "FHIR R4 schema adopted"),
        (16, "Credentialing pilot launched"),
        (22, "Provider self-service portal in pilot"),
        (26, "Quarterly attestation cadence live"),
    ),
)

_POLARIS = EngagementConfig(
    engagement_id="f5f5f5f5-f5f5-4f5f-8f5f-f5f5f5f5f5f5",
    name="Polaris Public Sector — Permit Portal Rebuild",
    customer_account="Polaris Public Sector",
    industry="public-sector",
    phase="build",
    namespace="polaris",
    stakeholders=(
        Stakeholder("ackerley", "Wilhelmina Ackerley", "Permit Division Director"),
        Stakeholder("oduwole", "Kayode Oduwole", "Director of Citizen Services"),
        Stakeholder("rasmusgaard", "Helle Rasmusgaard", "Solution Architect"),
        Stakeholder("petrov", "Iliya Petrov", "Identity & SSO Lead"),
        Stakeholder("morimoto", "Kanae Morimoto", "Accessibility Lead"),
        Stakeholder("delossantos", "Florencia de los Santos", "Procurement Officer"),
        Stakeholder("kindlmann", "Reinhard Kindlmann", "Security & Privacy"),
        Stakeholder("akande", "Bisola Akande", "Records Management"),
        Stakeholder("vasiljev", "Stanimir Vasiljev", "Legacy Systems Liaison"),
        Stakeholder("northrop", "Dahlia Northrop", "Communications Office"),
        Stakeholder("ehrhart", "Ottokar Ehrhart", "Inspector General Office"),
    ),
    departed_short_names=("vasiljev",),
    systems=(
        SystemTitle("Permit Portal (citizen-facing)", 1),
        SystemTitle("Permit Workflow Engine", 1),
        SystemTitle("State SSO (Login.gov)", 2),
        SystemTitle("Records Retention Service", 3),
        SystemTitle("Inspection Scheduling Module", 4),
        SystemTitle("Payment Gateway Adapter", 5),
    ),
    decision_titles=(
        (1, "Adopt Login.gov for citizen SSO"),
        (2, "Rebuild permit workflow on Camunda"),
        (3, "Mobile-first permit portal on Next.js"),
        (4, "Adopt USDS-aligned design system"),
        (5, "WCAG 2.2 AA conformance from day one"),
        (6, "Records retention on AWS GovCloud"),
        (7, "Spanish-language localization first"),
        (8, "Inspector scheduling rebuilt around shifts"),
        (9, "Payment gateway switch to NIC Inc."),
        (10, "Adopt open-data export pipeline"),
        (11, "FedRAMP Moderate baseline confirmed"),
        (12, "Adopt FOIA-friendly audit trail"),
        (13, "Multi-language SMS notifications"),
        (14, "Centralize permit type taxonomy"),
        (15, "Adopt inspector route optimization"),
        (16, "Tighten records destruction policy"),
        (17, "Defer business license module to phase 2"),
        (18, "Approve in-person assistance kiosk pilot"),
        (19, "Final WCAG audit sign-off"),
        (20, "Approve citizen permit dashboard"),
        (21, "Approve inspector mobile app rollout"),
        (22, "Approve open-data portal scope"),
        (23, "Approve regional rollout sequencing"),
        (24, "Approve permit data retention schedule"),
        (25, "Approve quarterly FOIA reporting cadence"),
    ),
    risk_titles=(
        (3, "Login.gov onboarding queue extending"),
        (4, "Camunda licensing terms still negotiating"),
        (5, "Accessibility audit backlog"),
        (6, "Records retention legal review pending"),
        (8, "FedRAMP Moderate ATO timeline"),
        (9, "Inspector mobile app field testing gaps"),
        (10, "Spanish localization vendor onboarding slow"),
        (11, "Citizen support team training behind"),
        (13, "FOIA audit trail completeness gaps"),
        (14, "Payment gateway PCI scope expanding"),
        (16, "Open data publishing cadence unclear"),
        (18, "Regional rollout staffing thin"),
        (20, "Citizen dashboard load testing pending"),
        (22, "Inspector route optimization model bias"),
        (23, "Permit type taxonomy disputed"),
    ),
    commitments=(
        (11, "FedRAMP Moderate authorization in progress"),
        (16, "Login.gov integration verified"),
        (22, "WCAG 2.2 AA audit complete"),
        (26, "Public launch communications signed off"),
    ),
)

PORTFOLIO_ENGAGEMENTS: tuple[EngagementConfig, ...] = (
    _NORTHWIND,
    _ACME_FIN,
    _GREENFIELD,
    _BEACON,
    _POLARIS,
)

PORTFOLIO_ENGAGEMENT_IDS: tuple[str, ...] = tuple(c.engagement_id for c in PORTFOLIO_ENGAGEMENTS)
