"""Emit Alembic expansion scaffolds for promoted schema proposals (Story 1-17)."""

from __future__ import annotations

import os
import uuid
from pathlib import Path

from control_plane.domain.canonical_memory.proposals import SchemaProposal


def _default_scaffold_root() -> Path:
    # .../src/control_plane/services/thisfile.py -> service root
    root = Path(__file__).resolve().parents[3]
    return root / "migrations" / "schema-proposals"


def scaffold_path_for(proposal_id: uuid.UUID) -> Path:
    base = os.environ.get("DEPLOYAI_SCHEMA_PROPOSAL_SCAFFOLD_DIR")
    if base:
        return Path(base) / f"{proposal_id}.py"
    return _default_scaffold_root() / f"{proposal_id}.py"


def write_promotion_scaffold(proposal: SchemaProposal) -> Path:
    """Create ``migrations/schema-proposals/<id>.py`` (expand step stub)."""
    path = scaffold_path_for(proposal.id)
    path.parent.mkdir(parents=True, exist_ok=True)
    rid = f"scaffold_{str(proposal.id).replace('-', '_')}"
    agent = (proposal.proposer_agent or "unknown").replace("\\", "\\\\").replace("'", "\\'")
    field_path = (proposal.proposed_field_path or "unknown").replace("\\", "\\\\").replace("'", "\\'")
    ptype = (proposal.proposed_type or "unknown").replace("\\", "\\\\").replace("'", "\\'")
    body = f'''\
# expand-contract: autogenerated scaffold (Story 1-17) — do not run blindly.
# proposal_id: {proposal.id}
# proposer_agent: {agent!r} proposed_field_path: {field_path!r} proposed_type: {ptype!r}
# Human review: fold into a real ``alembic/versions/`` expand revision.

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "{rid}"
down_revision: str | None = "20260424_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Replace with DDL matching ``proposed_ddl`` / field path from the proposal row.
    op.execute(sa.text("-- placeholder expand for proposal {proposal.id}"))


def downgrade() -> None:
    # Contract step after human review; keep stub so Alembic graph stays valid in editors.
    op.execute(sa.text("-- placeholder contract for proposal {proposal.id}"))
'''
    path.write_text(body, encoding="utf-8")
    return path
