"""Canonical memory ORM models (Story 1.8).

Every row in every table here carries:

- ``id`` — UUID v7 (K-sortable, time-ordered). Default generated by the
  Postgres function ``deployai_uuid_v7()`` created in migration
  ``20260422_0001``.
- ``tenant_id`` — ``UUID NOT NULL``. Story 1.9 adds RLS policies that
  enforce ``tenant_id = current_setting('app.current_tenant')::uuid``.
- ``created_at`` — ``TIMESTAMPTZ NOT NULL DEFAULT now()``.

``canonical_memory_events`` additionally enforces append-only semantics
via the ``canonical_memory_events_append_only`` trigger.

Story 1.8 is schema-only — repositories, tenant-scoped sessions, and
envelope encryption ship in Story 1.9.
"""

from control_plane.domain.canonical_memory.events import CanonicalMemoryEvent
from control_plane.domain.canonical_memory.identity import (
    IdentityAttributeHistory,
    IdentityNode,
    IdentitySupersession,
)
from control_plane.domain.canonical_memory.learnings import (
    LEARNING_STATES,
    LearningLifecycleState,
    LearningState,
    SolidifiedLearning,
)
from control_plane.domain.canonical_memory.proposals import SchemaProposal
from control_plane.domain.canonical_memory.tombstones import Tombstone

__all__ = [
    "LEARNING_STATES",
    "CanonicalMemoryEvent",
    "IdentityAttributeHistory",
    "IdentityNode",
    "IdentitySupersession",
    "LearningLifecycleState",
    "LearningState",
    "SchemaProposal",
    "SolidifiedLearning",
    "Tombstone",
]
