"""Shared SQLAlchemy declarative base for the control-plane domain layer.

The metadata attached here is what ``alembic/env.py`` hands to Alembic as
``target_metadata``. Importing any ORM module under
``control_plane.domain.canonical_memory`` registers its tables onto this
metadata so autogenerated migrations (Story 1.9+) see them.

Naming conventions match the architecture doc §"Database Naming":

- tables: snake_case plural
- indexes: ``idx_<table>_<cols>``
- RLS policies: ``tenant_rls_<table>`` (reserved — Story 1.9 wires them)
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION: dict[str, str] = {
    "ix": "idx_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every ORM-mapped canonical-memory table."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
