#!/usr/bin/env node
/**
 * Emits `artifacts/golden/coverage.html` for Story 4-4 (dashboard in CI / release).
 */
import { readFile, readdir, mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

import { PHASES, TOPOLOGIES, cellKey } from "./constants.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const QUERIES = join(__dirname, "..", "golden", "queries");
const OUT = join(__dirname, "..", "..", "artifacts", "golden", "coverage.html");

const counts = new Map();
for (const p of PHASES) for (const t of TOPOLOGIES) counts.set(cellKey(p, t), 0);

for (const name of await readdir(QUERIES)) {
  if (!name.endsWith(".yaml") && !name.endsWith(".yml")) continue;
  const doc = yaml.load(await readFile(join(QUERIES, name), "utf8"));
  if (!doc?.phase || !doc?.stakeholder_topology) continue;
  const k = cellKey(doc.phase, doc.stakeholder_topology);
  if (counts.has(k)) counts.set(k, (counts.get(k) || 0) + 1);
}

await mkdir(dirname(OUT), { recursive: true });
const rows = [...counts.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([c, n]) => `<tr><td>${c}</td><td>${n}</td></tr>`)
  .join("\n");
const html = `<!doctype html><html><head><meta charset="utf-8"><title>Golden matrix coverage</title>
<style>body{font-family:system-ui} table{border-collapse:collapse} td,th{border:1px solid #ccc;padding:6px}</style>
</head><body><h1>21-cell golden coverage</h1><table><thead><tr><th>cell</th><th>query count</th></tr></thead>
<tbody>${rows}</tbody></table><p>Generated by tests/golden-tools/coverage-html.mjs</p></body></html>`;
await writeFile(OUT, html, "utf8");
console.log(`Wrote ${OUT}`);
